### ISSUE TITLE
Any plans for OutWatch for ReasonML?

### ISSUE THREAD

**Issue by stereobooster** [OutWatch/purescript-outwatch#15]
Sorry for this totally offtopic question. I was just super curious. You already did it in two languages, which is awesome. Any plans for ReasonML?

**Comment by LukaJCB** [comment]
I'd love to at some point! But there's already so many things that should be done, so I can't really say if it's realistic right now :)

An idea I had was to take the common functionality from the two implementations and expose it using JavaScript and then only write wrappers for each language. Maybe even generate the wrappers.
