### ISSUE TITLE
website: minor overlap

### ISSUE THREAD

**Issue by rvion** [OutWatch/purescript-outwatch#4]
![image](https://cloud.githubusercontent.com/assets/2150990/24324767/4c55e07e-118c-11e7-8f33-d55d1bb38f21.png)

**Comment by LukaJCB** [comment]
Hey @rvion thanks a lot for reporting this, seems that sometimes the line doesn't break. I'll look into it shortly :)

**Comment by LukaJCB** [comment]
Fixed :)

**Comment by rvion** [comment]
is it deployed?

I see this at 100% size:

![image](https://cloud.githubusercontent.com/assets/2150990/24803045/446a233e-1baa-11e7-823f-156043fd4d5a.png)
